### ISSUE TITLE
Feature Request: Support GET for Random Serial

### ISSUE THREAD

**Issue by sleevi** [crtsh/ocsp_monitor#1]
If a server is implementing RFC 6960, with the Extended Revoke semantics of [Section 4.4.8](https://tools.ietf.org/html/rfc6960#section-4.4.8), the responder MUST include a non-critical response extension to indicate it is applying those semantics.

[Section 2.2](https://tools.ietf.org/html/rfc6960#section-2.2) highlights that, in situations where the responder pre-produces responses (e.g. for RFC 5019 deployment), they may not employ the Extended Revoke definition.

> For example, the
> responder may not have any knowledge about whether a requested
> serial number has been assigned to any issued certificate, or
> the responder may provide pre-produced responses in accordance
> with RFC 5019 and, for that reason, is not capable of providing
> a signed response for all non-issued certificate serial
> numbers.

Thus, there seems an opportunity where if an OCSP responder may respond differently to GET vs POST requests, particularly when employing CDNs as an intermediary between the CA's responder service. It'd be useful to exercise a GET to the random serial.

There's an argument for doing the GET and POST as the same serial, to see if they produce the same responses. However, it seems just as well that they could use distinct random serials, to ensure no cache inter-relationship between the objects.

**Comment by robstradling** [comment]
Thanks @sleevi.  Addressed by https://github.com/crtsh/ocsp_monitor/commit/77f79e3cc4acca1c6e8e8b38054c271e18aca9d2 and https://github.com/crtsh/certwatch_db/commit/ea980ca3fc43fa9a9a1ea55cd0a7bc12ee7f99b1
